version: '3.7'

services:
  # Spawns an nginx webserver with PHP-FPM and MySQL 5.7
  nginx:
    image: nginx:latest
    #restart: always
    ports:
      - 8000:80
      - 8443:443
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
    volumes:
      - ./:/public
      - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - development-network
    depends_on:
      - php
      - mysql57
    
  php:    
    build: 
      context: ./.docker
      dockerfile: Dockerfile-php
    #restart: always
    ports:
      - 9000:9000
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
    volumes:
      - ./:/public
    networks:
      - development-network

  mysql57:
    image: mysql:5.7
    #restart: always
    ports:
      - 3306:3306
      - 33060:33060
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - /var/lib/mysql57/data
    networks:
      - development-network
      
  mysql:
    image: mysql
    #restart: always
    ports:
      - 3306:3306
      - 33060:33060
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - /var/lib/mysql/data
    networks:
      - development-network
      
  postgres:
    image: postgres
    #restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - /var/lib/postgresql/data
    networks:
      - development-network
      
  adminer:
    image: adminer
    #restart: always
    ports:
      - 8080:8080
    networks:
      - development-network
  
  redis:
    image: redis
    #restart: always
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis/data
    networks:
      - development-network

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    #restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    networks:
      - development-network
    depends_on:
      - redis
      
  mongo:
    image: mongo
    #restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - /var/lib/mongo/data
    networks:
      - development-network

  mongo-express:
    image: mongo-express
    #restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    networks:
      - development-network
    depends_on:
      - mongo
      
  timescaledb:
    image: timescale/timescaledb:latest-pg11
    #restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - /var/lib/timescaledb/data
    networks:
      - development-network

networks:
  development-network:
    driver: bridge